#include "gepch.h"
#include "AssetManager.h"

#include "GanymedE/Assets/AssetMeta.h"
#include "GanymedE/Assets/AssetPaths.h"
#include "GanymedE/Assets/AssetWatcher.h"
#include "GanymedE/Assets/MaterialSerializer.h"
#include "GanymedE/Assets/CompiledCache.h"
#include "GanymedE/Assets/MeshCompiler.h"
#include "GanymedE/Assets/TextureCompiler.h"
#include "GanymedE/Assets/TextureImporter.h"
#include "GanymedE/Renderer/Environment.h"
#include "GanymedE/Renderer/Material.h"
#include "GanymedE/Renderer/MeshImporter.h"
#include "GanymedE/Renderer/MeshSource.h"
#include "GanymedE/Renderer/Texture.h"

#include <fstream>
#include <yaml-cpp/yaml.h>

namespace GanymedE {

	struct AssetManagerData
	{
		std::unordered_map<AssetHandle, AssetMetadata> Registry;
		std::unordered_map<std::string, AssetHandle> PathToHandle;

		bool Initialized = false;
		bool WritableRegistry = true;

		// path -> handle read out of the legacy assets/AssetRegistry.gr, kept for the whole
		// session rather than just for the scan. Files created *after* the scan need it too: a
		// `.gmat` regenerated by MaterialSerializer::GenerateSidecars, or a texture extracted
		// from a `.glb`, must adopt the handle the old registry recorded or every scene that
		// referenced it breaks. This is the one thing migration cannot get wrong.
		std::unordered_map<std::string, AssetHandle> LegacyHandles;
		bool LegacyRegistryPresent = false;

		// Handles already reported as unknown. RenderSystem re-fetches assets by handle
		// every frame per entity, so an unguarded warning here would arrive at frame
		// rate; once per handle is the AnimationSystem unknown-clip posture - loud, not
		// broken.
		std::unordered_set<AssetHandle> WarnedUnknownHandles;

		AssetApplyStats LastApply;
	};

	static AssetManagerData s_Data;

	// The two hooks TypedAssetManager<T>::Load needs from the facade. Declared in
	// AssetManagerRegistry.h rather than reached through AssetManager.h, because the
	// dependency runs the other way: GetAsset<T> is built on the manager template.
	namespace Detail {

		const AssetMetadata* FindAssetMetadata(AssetHandle handle)
		{
			return AssetManager::GetMetadata(handle);
		}

		// A valid handle with no registry entry means the scene references an asset this
		// install does not know about - almost always a `.meta` sidecar that did not travel
		// with its asset. Worth saying out loud: the consequence is an entity that renders
		// nothing, which is indistinguishable from a bad transform or an unlit material
		// until you know.
		void WarnUnknownAssetHandle(AssetHandle handle, const char* expectedTypeName)
		{
			if (!s_Data.WarnedUnknownHandles.insert(handle).second)
				return;

			GE_CORE_WARN("Asset handle {0} is not in the index (expected: {1}) - nothing will be "
				"loaded for it. The usual cause is an asset whose `.meta` sidecar did not travel "
				"with it, or a file that is no longer under assets/.",
				static_cast<uint64_t>(handle), expectedTypeName);
		}

	}

	namespace {

		struct ScanStats
		{
			std::size_t Adopted = 0;        // identity came from a sidecar
			std::size_t AdoptedLegacy = 0;  // identity came from the legacy AssetRegistry.gr
			std::size_t Minted = 0;         // no identity anywhere on disk, a new handle was made
			std::size_t Written = 0;        // sidecars created or refreshed
			std::size_t Quarantined = 0;
			std::size_t Collisions = 0;
			std::size_t TypeCorrected = 0;
		};

		// The one place a path becomes a handle. Both the scan and ImportAsset go through it, so
		// the sidecar rules - adopt, mint, collide, correct - exist once instead of twice.
		//
		// `stats` is null outside a scan; ImportAsset logs per call instead of in a summary.
		AssetHandle EnsureRegistered(const std::string& pathKey,
			const std::filesystem::path& fullPath, AssetType type, ScanStats* stats)
		{
			auto existing = s_Data.PathToHandle.find(pathKey);
			if (existing != s_Data.PathToHandle.end())
				return existing->second;

			AssetMeta meta;
			bool haveIdentity = false;
			bool needsWrite = false;

			switch (AssetMetaSerializer::Read(fullPath, meta))
			{
				case AssetMetaSerializer::ReadResult::Ok:
					haveIdentity = true;
					break;

				case AssetMetaSerializer::ReadResult::Missing:
					needsWrite = true;
					break;

				case AssetMetaSerializer::ReadResult::Corrupt:
				{
					// Quarantine rather than overwrite: one unreadable sidecar must not take
					// down a project scan, and the handle a hand-repair could recover is the
					// only link between this file and every scene referencing it.
					bool moved = s_Data.WritableRegistry && AssetMetaSerializer::Quarantine(fullPath);
					GE_CORE_ERROR("Asset sidecar for '{0}' failed to parse - the asset keeps "
						"working, but with a different handle unless the legacy registry still "
						"names it. The unreadable file was {1}.", pathKey,
						moved ? "kept as '" + AssetMetaSerializer::SidecarPath(fullPath).string() + ".bad'"
							  : "left in place (assets/ is read-only this session)");

					needsWrite = true;
					if (stats && moved)
						++stats->Quarantined;
					break;
				}
			}

			if (haveIdentity)
			{
				// A handle already claimed by another path is a real failure mode - a
				// copy-pasted `.meta`. First scanned wins and the second is re-minted, because
				// silently aliasing two assets to one handle corrupts every scene that
				// references either. Scan order is sorted, so which one wins is reproducible.
				auto claimed = s_Data.Registry.find(meta.Handle);
				if (claimed != s_Data.Registry.end())
				{
					GE_CORE_WARN("Assets '{0}' and '{1}' both claim handle {2} - keeping it for "
						"'{0}' and minting a fresh one for '{1}'. One of the two sidecars was "
						"copied; whichever asset now renders wrong is the one to re-point.",
						claimed->second.FilePath, pathKey, static_cast<uint64_t>(meta.Handle));

					haveIdentity = false;
					needsWrite = true;
					if (stats)
						++stats->Collisions;
				}
				else if (meta.Type != type)
				{
					// The extension is ground truth for *how* to load; the sidecar is ground
					// truth for *which* asset this is. Keep the identity, correct the type -
					// that is what a rename between two recognized extensions should cost.
					GE_CORE_WARN("Asset sidecar for '{0}' records type {1}, but its extension "
						"says {2} - keeping the handle and rewriting the type.", pathKey,
						AssetTypeToString(meta.Type), AssetTypeToString(type));

					meta.Type = type;
					needsWrite = true;
					if (stats)
						++stats->TypeCorrected;
				}
			}

			if (!haveIdentity)
			{
				meta = AssetMeta{};
				meta.Type = type;
				meta.ImportConfigVersion = CurrentImportConfigVersion;

				// Adopt the legacy handle when one exists and nothing else has taken it. This
				// is the whole of the migration: existing scenes keep resolving.
				// Counted apart from a fresh mint on purpose: on the one boot that performs the
				// migration, "adopted from the legacy registry" is the number that says it was
				// lossless. Folding the two together would hide a broken migration behind a
				// plausible-looking total.
				auto legacy = s_Data.LegacyHandles.find(pathKey);
				if (legacy != s_Data.LegacyHandles.end() && s_Data.Registry.count(legacy->second) == 0)
				{
					meta.Handle = legacy->second;
					if (stats)
						++stats->AdoptedLegacy;
				}
				else
				{
					meta.Handle = UUID();
					if (stats)
						++stats->Minted;
				}
			}
			else if (stats)
			{
				++stats->Adopted;
			}

			// No sidecar for a file that is not there. A scene naming a since-deleted asset
			// still gets an in-memory handle (unchanged behaviour, and its load path already
			// warns), but writing `foo.glb.meta` next to a missing `foo.glb` would leave an
			// orphan nothing ever cleans up.
			if (needsWrite && s_Data.WritableRegistry && std::filesystem::exists(fullPath))
			{
				if (AssetMetaSerializer::Write(fullPath, meta) && stats)
					++stats->Written;
			}

			AssetMetadata metadata;
			metadata.Handle = meta.Handle;
			metadata.Type = type;
			metadata.FilePath = pathKey;

			// Carried on the index entry so a compiler never re-reads the sidecar. Empty for an
			// asset whose sidecar had no Config block, which is every asset until an importer
			// setting is authored.
			metadata.Config = std::move(meta.Config);

			s_Data.Registry[metadata.Handle] = metadata;
			s_Data.PathToHandle[pathKey] = metadata.Handle;
			return metadata.Handle;
		}

	}

	void AssetManager::Init(bool writableAssets)
	{
		if (s_Data.Initialized)
			return;

		s_Data.WritableRegistry = writableAssets;

		// Before anything can load. Nothing in the scan does, but a manager slot that is empty
		// when GetAsset<T> reaches it asserts, and doing this first also makes the dense type
		// ids fall out of registration order rather than out of whichever call site ran first.
		RegisterManagers();

		// Legacy first, so the scan has a path -> handle seed to adopt from before it mints
		// anything. Reversing these two lines is how you break every existing scene.
		LoadLegacyRegistry();
		ScanAssets();

		// After the scan, so the first poll has an index to walk. Off wherever assets/ is
		// read-only: a shipped runtime has no editor to reload into and its content does not
		// change under it, so the poll would be pure cost.
		AssetWatcher::Init(writableAssets);

		s_Data.Initialized = true;
		GE_CORE_INFO("AssetManager initialized ({0} assets indexed, assets/ {1})",
			s_Data.Registry.size(), writableAssets ? "writable" : "read-only");

		if (s_Data.LegacyRegistryPresent && writableAssets)
		{
			GE_CORE_INFO("assets/AssetRegistry.gr is now redundant - identity lives in the "
				"`.meta` sidecars beside each asset, which are read at every boot and committed "
				"to source control. It is kept and still read for one release so a downgrade "
				"works; deleting it is yours to do.");
		}
	}

	void AssetManager::Shutdown()
	{
		if (!s_Data.Initialized)
			return;

		s_Data.Registry.clear();
		s_Data.PathToHandle.clear();
		s_Data.LegacyHandles.clear();
		s_Data.LegacyRegistryPresent = false;
		s_Data.WarnedUnknownHandles.clear();
		AssetWatcher::Shutdown();

		// Cancel first, then destroy. Every manager's in-flight parses are asked to stop before
		// any single Future's destructor starts waiting, so a shutdown with a scene's worth of
		// loads in flight drains them concurrently rather than one at a time.
		AssetManagerRegistry::ForEach([](IAssetManager& manager) { manager.CancelPending(); });

		// Destroys the managers, and with them everything they retain. Runs from
		// EditorLayer::OnDetach while Renderer::IsGpuAlive() is still true, so the GPU-resource
		// destructors release real bgfx handles rather than tripping the is-alive guard.
		AssetManagerRegistry::Clear();
		CompiledCache::Shutdown();
		s_Data.Initialized = false;
	}

	void AssetManager::ScanAssets()
	{
		const std::filesystem::path& root = GetAssetRoot();

		std::error_code ec;
		if (!std::filesystem::is_directory(root, ec))
		{
			GE_CORE_WARN("Asset root '{0}' does not exist - no assets were indexed. Every app "
				"resolves assets/ from its working directory, so this is usually a CWD problem.",
				std::filesystem::absolute(root).string());
			return;
		}

		// Collected first and sorted, rather than registered straight out of the iterator.
		// `recursive_directory_iterator`'s order is unspecified, and the duplicate-handle policy
		// is "first scanned wins" - left to the filesystem, two developers with the same
		// copy-pasted `.meta` would see different assets break. Sorting makes the outcome
		// reproducible, which is the only thing that makes the warning actionable.
		std::vector<std::filesystem::path> assetFiles;

		auto it = std::filesystem::recursive_directory_iterator(root,
			std::filesystem::directory_options::skip_permission_denied, ec);
		const auto end = std::filesystem::recursive_directory_iterator();

		for (; !ec && it != end; it.increment(ec))
		{
			const std::filesystem::path& path = it->path();

			if (it->is_directory(ec))
			{
				// Skip dotted directories whole: `.assets` (the mesh cache) today, `.compiled`
				// once Phase 4 lands. Derived output is never asset identity, and not walking it
				// is what keeps the scan's cost proportional to authored content.
				std::string name = path.filename().string();
				if (!name.empty() && name.front() == '.')
					it.disable_recursion_pending();
				continue;
			}

			if (AssetMetaSerializer::IsSidecarPath(path))
				continue;

			if (AssetTypeFromExtension(path.extension().string()) == AssetType::None)
				continue;

			assetFiles.push_back(path);
		}

		if (ec)
		{
			GE_CORE_ERROR("Walking '{0}' failed: {1} - {2} assets were indexed before it stopped.",
				root.string(), ec.message(), assetFiles.size());
		}

		std::sort(assetFiles.begin(), assetFiles.end());

		ScanStats stats;
		for (const std::filesystem::path& fullPath : assetFiles)
		{
			std::string pathKey = MakeAssetRelative(fullPath).generic_string();
			AssetType type = AssetTypeFromExtension(fullPath.extension().string());
			EnsureRegistered(pathKey, fullPath, type, &stats);
		}

		// Deliberately one INFO line with every counter on it: "did this boot mint anything?"
		// is the question a scan-derived index has to be able to answer at a glance, and a
		// second run over an unchanged tree must read 0 minted, 0 written.
		GE_CORE_INFO("Asset scan: {0} files, {1} adopted from sidecars, {2} adopted from the legacy "
			"registry, {3} handles minted, {4} sidecars written, {5} quarantined, {6} handle "
			"collisions, {7} types corrected",
			assetFiles.size(), stats.Adopted, stats.AdoptedLegacy, stats.Minted, stats.Written,
			stats.Quarantined, stats.Collisions, stats.TypeCorrected);
	}

	AssetHandle AssetManager::ImportAsset(const std::filesystem::path& relativePath)
	{
		std::string pathKey = relativePath.generic_string();
		auto existing = s_Data.PathToHandle.find(pathKey);
		if (existing != s_Data.PathToHandle.end())
			return existing->second;

		AssetType type = AssetTypeFromExtension(relativePath.extension().string());
		if (type == AssetType::None)
		{
			GE_CORE_WARN("Unsupported asset type for '{0}'", pathKey);
			return InvalidAssetHandle;
		}

		// Reached only for a file the scan did not see - one created since (an extracted `.glb`
		// texture, a generated `.gmat`) or one a scene names that is not on disk.
		AssetHandle handle = EnsureRegistered(pathKey, GetAssetRoot() / relativePath, type, nullptr);
		GE_CORE_INFO("Imported asset '{0}' as {1} (handle {2})",
			pathKey, AssetTypeToString(type), static_cast<uint64_t>(handle));

		return handle;
	}

	AssetHandle AssetManager::GetHandle(const std::filesystem::path& relativePath)
	{
		std::string pathKey = relativePath.generic_string();
		auto it = s_Data.PathToHandle.find(pathKey);
		if (it != s_Data.PathToHandle.end())
			return it->second;
		return InvalidAssetHandle;
	}

	const AssetMetadata* AssetManager::GetMetadata(AssetHandle handle)
	{
		auto it = s_Data.Registry.find(handle);
		if (it == s_Data.Registry.end())
			return nullptr;
		return &it->second;
	}

	AssetType AssetManager::GetAssetType(AssetHandle handle)
	{
		const AssetMetadata* metadata = GetMetadata(handle);
		return metadata ? metadata->Type : AssetType::None;
	}

	void AssetManager::ForEachAsset(const std::function<void(const AssetMetadata&)>& fn)
	{
		for (const auto& entry : s_Data.Registry)
			fn(entry.second);
	}

	namespace {

		// ---- Compiled blob ------------------------------------------------------------
		//
		// Every Parse below runs on a worker: it opens the compiled artifact, compiling it first
		// if the epoch record says it is stale. Nothing here may touch bgfx, and since Phase 5
		// nothing does - the mesh compiler was the last holdout and MeshSource split it.
		struct CompiledBlob : AssetParseResult
		{
			std::vector<uint8_t> Bytes;
		};

		Scope<AssetParseResult> ParseTexture(const AssetMetadata& metadata)
		{
			auto parsed = CreateScope<CompiledBlob>();
			if (!CompiledCache::Open(metadata, parsed->Bytes) || parsed->Bytes.empty())
				return nullptr;

			return parsed;
		}

		// ---- Mesh ---------------------------------------------------------------------
		struct MeshParse : AssetParseResult
		{
			MeshSource Source;
		};

		Scope<AssetParseResult> ParseMesh(const AssetMetadata& metadata)
		{
			std::vector<uint8_t> blob;
			if (!CompiledCache::Open(metadata, blob) || blob.empty())
				return nullptr;

			auto parsed = CreateScope<MeshParse>();
			if (!MeshCompiler::Read(blob, metadata.FilePath, parsed->Source))
				return nullptr;

			// The expensive half of what Apply used to do. Images embedded in a `.glb` have no
			// file and therefore no asset handle, so they cannot go through the texture manager;
			// they used to be stb-decoded inside BuildMesh, on the submit thread, at 50-60 ms for
			// a 1K texture. Decoding here leaves Apply with the upload alone.
			if (!DecodeEmbeddedMaps(parsed->Source))
				return nullptr;   // cancelled; the result is discarded without reaching Apply

			return parsed;
		}

		Ref<Mesh> ApplyMesh(const AssetMetadata& metadata, Scope<AssetParseResult> parsed)
		{
			const std::filesystem::path relativePath = metadata.FilePath;

			Ref<Mesh> mesh = BuildMesh(static_cast<MeshParse&>(*parsed).Source);
			if (!mesh)
				return nullptr;

			// Here rather than inside MeshImporter, because this is the one point both the cold
			// import and the cache replay pass through - a cached mesh must still get its
			// sidecars, or deleting .meshcache would be the only way to regenerate them.
			//
			// It now runs *before* the manager caches the mesh, where the old code ran after.
			// Safe because GenerateSidecars only ever reaches ImportAsset, never GetAsset<Mesh>:
			// it writes files and registers handles, so nothing in it can re-enter this load.
			MaterialSerializer::GenerateSidecars(mesh, relativePath);
			return mesh;
		}

		// ---- Environment --------------------------------------------------------------
		//
		// The claim that used to sit here - that the separable CPU part is "a few percent" of an
		// environment load - was wrong, and measuring it is what closed the last synchronous
		// hitch in the asset layer. Release, 1K panorama: `stbi_loadf` **25 ms**, the bake's own
		// submission 2 ms. The decode was 45% of it, and it is exactly the kind of work Parse
		// exists for.
		struct EnvironmentParse : AssetParseResult
		{
			EquirectImage Image;
		};

		Scope<AssetParseResult> ParseEnvironment(const AssetMetadata& metadata)
		{
			auto parsed = CreateScope<EnvironmentParse>();
			parsed->Image = Environment::Load((GetAssetRoot() / metadata.FilePath).string());
			if (!parsed->Image.IsValid())
				return nullptr;

			return parsed;
		}

		// What is left here is the part that genuinely cannot move: uploading the panorama and
		// submitting the bake, both bgfx calls on the thread that owns the context.
		Ref<Environment> ApplyEnvironment(const AssetMetadata& metadata, Scope<AssetParseResult> parsed)
		{
			return Environment::Create((GetAssetRoot() / metadata.FilePath).string(),
				std::move(static_cast<EnvironmentParse&>(*parsed).Image));
		}

		// ---- Texture ------------------------------------------------------------------
		//
		// The clean case, and the one that pays twice: Parse is a file read (or a BC7 encode on
		// a cold tree) with no bgfx call anywhere below it, and what Apply uploads is a mipped,
		// block-compressed container rather than a decoded RGBA8 buffer.
		Ref<Texture2D> ApplyTexture(const AssetMetadata&, Scope<AssetParseResult> parsed)
		{
			const std::vector<uint8_t>& bytes = static_cast<CompiledBlob&>(*parsed).Bytes;
			return Texture2D::CreateFromContainer(bytes.data(), (uint32_t)bytes.size());
		}

		// ---- Material -----------------------------------------------------------------
		//
		// Cached, not path-resolved (the Script/Audio pattern), and the caching is load-bearing
		// rather than a performance choice: instancing merges draws on Ref<Material> *identity*,
		// so two entities sharing one .gmat handle must receive the same Ref or every batch
		// shatters. That is also why Material cannot be given a shared placeholder in Phase 5
		// without thinking about batching first.
		struct MaterialParse : AssetParseResult
		{
			MaterialDesc Desc;
		};

		Scope<AssetParseResult> ParseMaterial(const AssetMetadata& metadata)
		{
			auto parsed = CreateScope<MaterialParse>();
			if (!MaterialSerializer::ReadDesc(GetAssetRoot() / metadata.FilePath, parsed->Desc))
				return nullptr;

			return parsed;
		}

		Ref<Material> ApplyMaterial(const AssetMetadata&, Scope<AssetParseResult> parsed)
		{
			return MaterialSerializer::Build(static_cast<MaterialParse&>(*parsed).Desc);
		}

	}

	void AssetManager::RegisterManagers()
	{
		// The order fixes the dense type ids for this run and has no other meaning; the ids are
		// never persisted, because AssetType - stored by name in a `.meta` - is the durable
		// form. The AssetType each manager serves comes from AssetTypeOf<T>, so this list cannot
		// disagree with the GE_ASSET_TYPE declarations; a type missing from those does not
		// compile here.
		AssetManagerRegistry::Register<Mesh>("Mesh", &ParseMesh, &ApplyMesh);

		AssetManagerRegistry::Register<Environment>("Environment", &ParseEnvironment, &ApplyEnvironment);
		AssetManagerRegistry::Register<Texture2D>("Texture2D", &ParseTexture, &ApplyTexture);
		AssetManagerRegistry::Register<Material>("Material", &ParseMaterial, &ApplyMaterial);

		// Which types have an offline step. A type absent from this list still loads - the cache
		// hands back its source bytes untouched - which is the right answer for `.hdr`
		// environments, whose expensive part is a GPU bake that cannot be precomputed, and for
		// `.gmat` materials, which are already the compact form of themselves.
		CompiledCache::RegisterCompiler(AssetType::StaticMesh, CreateScope<MeshCompiler>());
		CompiledCache::RegisterCompiler(AssetType::Texture, CreateScope<TextureCompiler>());
	}

	void AssetManager::Reload(AssetHandle handle)
	{
		const AssetMetadata* metadata = GetMetadata(handle);
		if (!metadata)
			return;

		// Scene, Script, Audio and Prefab have no manager, so there is nothing to evict - they
		// are path-resolved and their consumers own whatever caching they do.
		IAssetManager* manager = AssetManagerRegistry::Find(metadata->Type);
		if (!manager)
			return;

		// Textures go first, then their owner. Weak caching did not make this ordering
		// unnecessary, which is worth stating because it is tempting to assume it did: the
		// reloaded material or mesh re-resolves its map paths through LoadMaterialMap, which is
		// a GetAsset<Texture2D>, and a texture still cached would be handed straight back. The
		// rule is about the texture cache, not about who owns the material.
		auto evictMaps = [](const Ref<Material>& material)
		{
			if (!material)
				return;

			for (const std::string* mapPath : {
				&material->GetAlbedoMapPath(),
				&material->GetNormalMapPath(),
				&material->GetMetallicRoughnessMapPath() })
			{
				if (mapPath->empty())
					continue;

				AssetHandle textureHandle = GetHandle(*mapPath);
				if (IsAssetHandleValid(textureHandle))
					AssetManagerRegistry::Get<Texture2D>().Evict(textureHandle);
			}
		};

		if (metadata->Type == AssetType::Texture)
		{
			// A texture's compiled output is the thing that has to go: evicting the object alone
			// would re-open the same stale `.gres`. Every other type reaches Invalidate through
			// its own branch or does not have one.
			CompiledCache::Invalidate(*metadata);
		}
		else if (metadata->Type == AssetType::Material)
		{
			evictMaps(AssetManagerRegistry::Get<Material>().Find(handle));
		}
		else if (metadata->Type == AssetType::StaticMesh)
		{
			if (Ref<Mesh> mesh = AssetManagerRegistry::Get<Mesh>().Find(handle))
			{
				for (const Ref<Material>& material : mesh->GetMaterials())
					evictMaps(material);
			}

			// The epoch record already catches an edited source; this covers "reimport now",
			// where the source is untouched but the result should be rebuilt anyway.
			CompiledCache::Invalidate(*metadata);
		}

		manager->Evict(handle);
		GE_CORE_INFO("Reloading asset '{0}'", metadata->FilePath);
	}

	namespace {

		bool UsesTexture(const Material& material, AssetHandle texture)
		{
			return material.GetAlbedoMapHandle() == texture
				|| material.GetNormalMapHandle() == texture
				|| material.GetMetallicRoughnessMapHandle() == texture;
		}

		// The reverse edge hot reload needs: this texture changed, so everything that *captured*
		// it has to be rebuilt. Depth-1, and computed by scanning what is resident rather than
		// maintained as a map.
		//
		// Roadmap decision 11 asks for an `unordered_map<AssetHandle, vector<AssetHandle>>`
		// populated as assets load. Scanning is the better shape here for one specific reason:
		// the cache is **weak**, so "which materials reference this texture" is only ever a
		// question about *resident* objects. A maintained map would accumulate edges to objects
		// that have since been collected, and the weak cache offers no hook to prune them - the
		// map would need sweeping on every eviction and would still be wrong between sweeps. The
		// scan cannot go stale, needs no bookkeeping on the load path, and costs three handle
		// compares per resident material: a scene's worth of assets is a few hundred integer
		// comparisons, at the rate a human saves a file.
		//
		// The rule this exists to enforce is stated in docs/engine/assets.md: hold an
		// `AssetRef<T>`, not a `Ref<T>`. Material and Mesh are the two places the engine breaks
		// it - a Material captures `Ref<Texture2D>`, a Mesh owns its `Ref<Material>`s outright -
		// and they break it for good reasons, so this is the price.
		void EvictTextureDependents(AssetHandle texture)
		{
			// Collected before anything is evicted: Evict erases from the very caches these
			// walks iterate.
			std::vector<AssetHandle> materials;
			AssetManagerRegistry::Get<Material>().ForEachResident(
				[&](AssetHandle handle, const Ref<Material>& material)
				{
					if (UsesTexture(*material, texture))
						materials.push_back(handle);
				});

			// A mesh's materials are built by BuildMesh out of the compiled blob's material
			// *descriptions*, not resolved from `.gmat` handles - so the mesh is the only thing
			// that can re-resolve them, and evicting the whole mesh is how. Cheap: the blob is a
			// cache hit, so this is a file read and a buffer upload rather than a re-import.
			std::vector<AssetHandle> meshes;
			AssetManagerRegistry::Get<Mesh>().ForEachResident(
				[&](AssetHandle handle, const Ref<Mesh>& mesh)
				{
					for (const Ref<Material>& material : mesh->GetMaterials())
					{
						if (material && UsesTexture(*material, texture))
						{
							meshes.push_back(handle);
							break;
						}
					}
				});

			for (AssetHandle handle : materials)
				AssetManagerRegistry::Get<Material>().Evict(handle);

			for (AssetHandle handle : meshes)
				AssetManagerRegistry::Get<Mesh>().Evict(handle);

			if (!materials.empty() || !meshes.empty())
			{
				GE_CORE_TRACE("Hot reload: {0} material(s) and {1} mesh(es) rebuild for it",
					materials.size(), meshes.size());
			}
		}

	}

	bool AssetManager::OnAssetModified(AssetHandle handle)
	{
		const AssetMetadata* metadata = GetMetadata(handle);
		if (!metadata)
			return false;

		// Scene, Script, Audio and Prefab have no manager and nothing cached here: Lua owns its
		// chunks and miniaudio owns decoded audio. Saving a `.ganymede` from the editor lands
		// here every time, so this is also what keeps the log quiet.
		IAssetManager* manager = AssetManagerRegistry::Find(metadata->Type);
		if (!manager)
			return false;

		manager->Evict(handle);

		// Nothing re-resolves between these two calls - Evict only drops cache entries and bumps
		// the epoch - so the whole set is evicted before any Get() can hand back a stale object.
		if (metadata->Type == AssetType::Texture)
			EvictTextureDependents(handle);

		// Deliberately **no** CompiledCache::Invalidate. Reload calls it because it means
		// "reimport now"; a file event does not. The epoch record already distinguishes an edit
		// from a rewrite that lands identical bytes, and editors save by writing a temp file and
		// renaming constantly - forcing a recompile on every mtime move would turn a
		// no-op save of a 2K texture into a multi-second BC7 encode. This is the case Phase 4's
		// content hashing was built for.
		return true;
	}

	namespace {

		// The asset layer's share of a frame for main-thread Apply work.
		//
		// Deliberately a constant rather than a setter. There is one call site, nothing has yet
		// wanted a different number, and a knob nobody turns is worse than a number with a reason
		// next to it. 4 ms is a quarter of a 60 Hz frame: enough that a handful of cheap applies
		// still land together, small enough that a burst spreads over frames instead of stalling
		// one. The budget is the asset layer's own allowance, not "whatever is left of the frame" -
		// it does not know what else the frame has spent, and making it guess would trade a
		// predictable cost for an erratic one.
		constexpr double kApplyBudgetMs = 4.0;

	}

	void AssetManager::Update()
	{
		GE_PROFILE_FUNCTION();

		// Before the managers, and before anything in the frame reads an asset. Evicting here
		// means a `Ref` obtained later in this frame cannot be pulled out from under it, which
		// is the plan's "apply reloads at a frame boundary" satisfied by construction.
		AssetWatcher::Poll();

		// One budget across every manager. They are visited in registration order, so a manager
		// with expensive work can use the whole allowance and leave the later ones nothing this
		// frame. That is acceptable and mildly useful: Mesh is first, so geometry appears before
		// the textures that dress it, and the work is finite either way.
		ApplyBudget budget(kApplyBudgetMs);
		AssetManagerRegistry::ForEach([&budget](IAssetManager& manager) { manager.Update(budget); });

		s_Data.LastApply.Applied = budget.Applied();
		s_Data.LastApply.Deferred = budget.Deferred();
		s_Data.LastApply.Milliseconds = budget.ElapsedMs();
		s_Data.LastApply.BudgetMs = kApplyBudgetMs;
	}

	AssetApplyStats AssetManager::GetApplyStats()
	{
		return s_Data.LastApply;
	}

	void AssetManager::WaitFor(AssetHandle handle)
	{
		const AssetMetadata* metadata = GetMetadata(handle);
		if (!metadata)
			return;

		if (IAssetManager* manager = AssetManagerRegistry::Find(metadata->Type))
			manager->WaitFor(handle);
	}

	std::size_t AssetManager::PendingCount()
	{
		std::size_t count = 0;
		AssetManagerRegistry::ForEach([&count](IAssetManager& manager) { count += manager.PendingCount(); });
		return count;
	}

	std::vector<AssetCacheStats> AssetManager::GetCacheStats()
	{
		std::vector<AssetCacheStats> stats;
		AssetManagerRegistry::ForEach([&stats](IAssetManager& manager)
		{
			stats.push_back({ manager.TypeName(), manager.ResidentCount(),
				manager.TrackedCount(), manager.PendingCount() });
		});

		return stats;
	}

	void AssetManager::LoadLegacyRegistry()
	{
		std::filesystem::path registryPath = GetAssetRoot() / "AssetRegistry.gr";
		if (!std::filesystem::exists(registryPath))
			return;

		s_Data.LegacyRegistryPresent = true;

		std::stringstream buffer;
		{
			std::ifstream stream(registryPath);
			if (!stream)
				return;

			buffer << stream.rdbuf();
		}

		YAML::Node assets;
		try
		{
			// Same posture as SceneSerializer::Deserialize: malformed content is something to
			// report, not a reason to take the process down. Unhandled, a truncated `.gr`
			// terminated the process out of Init - before a window existed to say why.
			YAML::Node root = YAML::Load(buffer.str());
			assets = root["Assets"];
		}
		catch (const YAML::Exception& e)
		{
			// The file is *not* quarantined, unlike before: nothing overwrites it any more, so
			// leaving it in place is what lets a hand-repair work. What matters instead is that
			// the session must not bake a lossy migration into the tree. An unreadable seed
			// means every asset would mint a fresh handle and write a sidecar claiming it -
			// permanently breaking every scene that referenced the old one. So the session goes
			// read-only: handles still work in memory, nothing is persisted, and fixing the file
			// and restarting recovers completely.
			s_Data.WritableRegistry = false;

			GE_CORE_ERROR("Legacy asset registry '{0}' failed to parse: {1}. assets/ is "
				"read-only for this session so no `.meta` sidecar can be written from a broken "
				"seed - every asset would otherwise adopt a new handle and every existing scene "
				"would stop resolving. Repair or delete the file and restart.",
				registryPath.string(), e.what());
			return;
		}

		if (!assets)
			return;

		for (auto assetNode : assets)
		{
			// `Type` is read past, not read: the extension is what types an asset now, and the
			// by-ordinal enum this file persisted is exactly the trap the sidecar format does
			// not inherit. Only identity is migrated.
			if (!assetNode["Handle"] || !assetNode["FilePath"])
				continue;

			AssetHandle handle = AssetHandle(assetNode["Handle"].as<uint64_t>());
			std::string filePath = assetNode["FilePath"].as<std::string>();

			auto existing = s_Data.LegacyHandles.find(filePath);
			if (existing != s_Data.LegacyHandles.end())
			{
				GE_CORE_WARN("Legacy asset registry has duplicate entries for '{0}' (handles {1} "
					"and {2}); adopting {1}", filePath,
					static_cast<uint64_t>(existing->second), static_cast<uint64_t>(handle));
				continue;
			}

			s_Data.LegacyHandles[filePath] = handle;
		}

		GE_CORE_TRACE("Legacy asset registry read ({0} handles available to adopt)",
			s_Data.LegacyHandles.size());
	}

	bool AssetManager::IsRegistryWritable()
	{
		return s_Data.WritableRegistry;
	}

}
