#include "gepch.h"
#include "AssetManager.h"

#include "GanymedE/Assets/AssetMeta.h"
#include "GanymedE/Assets/AssetPaths.h"
#include "GanymedE/Assets/MaterialSerializer.h"
#include "GanymedE/Assets/MeshCache.h"
#include "GanymedE/Assets/TextureImporter.h"
#include "GanymedE/Renderer/Environment.h"
#include "GanymedE/Renderer/Material.h"
#include "GanymedE/Renderer/MeshImporter.h"
#include "GanymedE/Renderer/Texture.h"

#include <fstream>
#include <yaml-cpp/yaml.h>

namespace GanymedE {

	struct AssetManagerData
	{
		std::unordered_map<AssetHandle, AssetMetadata> Registry;
		std::unordered_map<std::string, AssetHandle> PathToHandle;

		bool Initialized = false;
		bool WritableRegistry = true;

		// path -> handle read out of the legacy assets/AssetRegistry.gr, kept for the whole
		// session rather than just for the scan. Files created *after* the scan need it too: a
		// `.gmat` regenerated by MaterialSerializer::GenerateSidecars, or a texture extracted
		// from a `.glb`, must adopt the handle the old registry recorded or every scene that
		// referenced it breaks. This is the one thing migration cannot get wrong.
		std::unordered_map<std::string, AssetHandle> LegacyHandles;
		bool LegacyRegistryPresent = false;

		// Handles already reported as unknown. RenderSystem re-fetches assets by handle
		// every frame per entity, so an unguarded warning here would arrive at frame
		// rate; once per handle is the AnimationSystem unknown-clip posture - loud, not
		// broken.
		std::unordered_set<AssetHandle> WarnedUnknownHandles;
	};

	static AssetManagerData s_Data;

	// The two hooks TypedAssetManager<T>::Load needs from the facade. Declared in
	// AssetManagerRegistry.h rather than reached through AssetManager.h, because the
	// dependency runs the other way: GetAsset<T> is built on the manager template.
	namespace Detail {

		const AssetMetadata* FindAssetMetadata(AssetHandle handle)
		{
			return AssetManager::GetMetadata(handle);
		}

		// A valid handle with no registry entry means the scene references an asset this
		// install does not know about - almost always a `.meta` sidecar that did not travel
		// with its asset. Worth saying out loud: the consequence is an entity that renders
		// nothing, which is indistinguishable from a bad transform or an unlit material
		// until you know.
		void WarnUnknownAssetHandle(AssetHandle handle, const char* expectedTypeName)
		{
			if (!s_Data.WarnedUnknownHandles.insert(handle).second)
				return;

			GE_CORE_WARN("Asset handle {0} is not in the index (expected: {1}) - nothing will be "
				"loaded for it. The usual cause is an asset whose `.meta` sidecar did not travel "
				"with it, or a file that is no longer under assets/.",
				static_cast<uint64_t>(handle), expectedTypeName);
		}

	}

	namespace {

		struct ScanStats
		{
			std::size_t Adopted = 0;        // identity came from a sidecar
			std::size_t AdoptedLegacy = 0;  // identity came from the legacy AssetRegistry.gr
			std::size_t Minted = 0;         // no identity anywhere on disk, a new handle was made
			std::size_t Written = 0;        // sidecars created or refreshed
			std::size_t Quarantined = 0;
			std::size_t Collisions = 0;
			std::size_t TypeCorrected = 0;
		};

		// The one place a path becomes a handle. Both the scan and ImportAsset go through it, so
		// the sidecar rules - adopt, mint, collide, correct - exist once instead of twice.
		//
		// `stats` is null outside a scan; ImportAsset logs per call instead of in a summary.
		AssetHandle EnsureRegistered(const std::string& pathKey,
			const std::filesystem::path& fullPath, AssetType type, ScanStats* stats)
		{
			auto existing = s_Data.PathToHandle.find(pathKey);
			if (existing != s_Data.PathToHandle.end())
				return existing->second;

			AssetMeta meta;
			bool haveIdentity = false;
			bool needsWrite = false;

			switch (AssetMetaSerializer::Read(fullPath, meta))
			{
				case AssetMetaSerializer::ReadResult::Ok:
					haveIdentity = true;
					break;

				case AssetMetaSerializer::ReadResult::Missing:
					needsWrite = true;
					break;

				case AssetMetaSerializer::ReadResult::Corrupt:
				{
					// Quarantine rather than overwrite: one unreadable sidecar must not take
					// down a project scan, and the handle a hand-repair could recover is the
					// only link between this file and every scene referencing it.
					bool moved = s_Data.WritableRegistry && AssetMetaSerializer::Quarantine(fullPath);
					GE_CORE_ERROR("Asset sidecar for '{0}' failed to parse - the asset keeps "
						"working, but with a different handle unless the legacy registry still "
						"names it. The unreadable file was {1}.", pathKey,
						moved ? "kept as '" + AssetMetaSerializer::SidecarPath(fullPath).string() + ".bad'"
							  : "left in place (assets/ is read-only this session)");

					needsWrite = true;
					if (stats && moved)
						++stats->Quarantined;
					break;
				}
			}

			if (haveIdentity)
			{
				// A handle already claimed by another path is a real failure mode - a
				// copy-pasted `.meta`. First scanned wins and the second is re-minted, because
				// silently aliasing two assets to one handle corrupts every scene that
				// references either. Scan order is sorted, so which one wins is reproducible.
				auto claimed = s_Data.Registry.find(meta.Handle);
				if (claimed != s_Data.Registry.end())
				{
					GE_CORE_WARN("Assets '{0}' and '{1}' both claim handle {2} - keeping it for "
						"'{0}' and minting a fresh one for '{1}'. One of the two sidecars was "
						"copied; whichever asset now renders wrong is the one to re-point.",
						claimed->second.FilePath, pathKey, static_cast<uint64_t>(meta.Handle));

					haveIdentity = false;
					needsWrite = true;
					if (stats)
						++stats->Collisions;
				}
				else if (meta.Type != type)
				{
					// The extension is ground truth for *how* to load; the sidecar is ground
					// truth for *which* asset this is. Keep the identity, correct the type -
					// that is what a rename between two recognized extensions should cost.
					GE_CORE_WARN("Asset sidecar for '{0}' records type {1}, but its extension "
						"says {2} - keeping the handle and rewriting the type.", pathKey,
						AssetTypeToString(meta.Type), AssetTypeToString(type));

					meta.Type = type;
					needsWrite = true;
					if (stats)
						++stats->TypeCorrected;
				}
			}

			if (!haveIdentity)
			{
				meta = AssetMeta{};
				meta.Type = type;
				meta.ImportConfigVersion = CurrentImportConfigVersion;

				// Adopt the legacy handle when one exists and nothing else has taken it. This
				// is the whole of the migration: existing scenes keep resolving.
				// Counted apart from a fresh mint on purpose: on the one boot that performs the
				// migration, "adopted from the legacy registry" is the number that says it was
				// lossless. Folding the two together would hide a broken migration behind a
				// plausible-looking total.
				auto legacy = s_Data.LegacyHandles.find(pathKey);
				if (legacy != s_Data.LegacyHandles.end() && s_Data.Registry.count(legacy->second) == 0)
				{
					meta.Handle = legacy->second;
					if (stats)
						++stats->AdoptedLegacy;
				}
				else
				{
					meta.Handle = UUID();
					if (stats)
						++stats->Minted;
				}
			}
			else if (stats)
			{
				++stats->Adopted;
			}

			// No sidecar for a file that is not there. A scene naming a since-deleted asset
			// still gets an in-memory handle (unchanged behaviour, and its load path already
			// warns), but writing `foo.glb.meta` next to a missing `foo.glb` would leave an
			// orphan nothing ever cleans up.
			if (needsWrite && s_Data.WritableRegistry && std::filesystem::exists(fullPath))
			{
				if (AssetMetaSerializer::Write(fullPath, meta) && stats)
					++stats->Written;
			}

			AssetMetadata metadata;
			metadata.Handle = meta.Handle;
			metadata.Type = type;
			metadata.FilePath = pathKey;

			s_Data.Registry[metadata.Handle] = metadata;
			s_Data.PathToHandle[pathKey] = metadata.Handle;
			return metadata.Handle;
		}

	}

	void AssetManager::Init(bool writableAssets)
	{
		if (s_Data.Initialized)
			return;

		s_Data.WritableRegistry = writableAssets;

		// Before anything can load. Nothing in the scan does, but a manager slot that is empty
		// when GetAsset<T> reaches it asserts, and doing this first also makes the dense type
		// ids fall out of registration order rather than out of whichever call site ran first.
		RegisterManagers();

		// Legacy first, so the scan has a path -> handle seed to adopt from before it mints
		// anything. Reversing these two lines is how you break every existing scene.
		LoadLegacyRegistry();
		ScanAssets();

		s_Data.Initialized = true;
		GE_CORE_INFO("AssetManager initialized ({0} assets indexed, assets/ {1})",
			s_Data.Registry.size(), writableAssets ? "writable" : "read-only");

		if (s_Data.LegacyRegistryPresent && writableAssets)
		{
			GE_CORE_INFO("assets/AssetRegistry.gr is now redundant - identity lives in the "
				"`.meta` sidecars beside each asset, which are read at every boot and committed "
				"to source control. It is kept and still read for one release so a downgrade "
				"works; deleting it is yours to do.");
		}
	}

	void AssetManager::Shutdown()
	{
		if (!s_Data.Initialized)
			return;

		s_Data.Registry.clear();
		s_Data.PathToHandle.clear();
		s_Data.LegacyHandles.clear();
		s_Data.LegacyRegistryPresent = false;
		s_Data.WarnedUnknownHandles.clear();
		// Destroys the managers, and with them everything they retain. Runs from
		// EditorLayer::OnDetach while Renderer::IsGpuAlive() is still true, so the GPU-resource
		// destructors release real bgfx handles rather than tripping the is-alive guard.
		AssetManagerRegistry::Clear();
		s_Data.Initialized = false;
	}

	void AssetManager::ScanAssets()
	{
		const std::filesystem::path& root = GetAssetRoot();

		std::error_code ec;
		if (!std::filesystem::is_directory(root, ec))
		{
			GE_CORE_WARN("Asset root '{0}' does not exist - no assets were indexed. Every app "
				"resolves assets/ from its working directory, so this is usually a CWD problem.",
				std::filesystem::absolute(root).string());
			return;
		}

		// Collected first and sorted, rather than registered straight out of the iterator.
		// `recursive_directory_iterator`'s order is unspecified, and the duplicate-handle policy
		// is "first scanned wins" - left to the filesystem, two developers with the same
		// copy-pasted `.meta` would see different assets break. Sorting makes the outcome
		// reproducible, which is the only thing that makes the warning actionable.
		std::vector<std::filesystem::path> assetFiles;

		auto it = std::filesystem::recursive_directory_iterator(root,
			std::filesystem::directory_options::skip_permission_denied, ec);
		const auto end = std::filesystem::recursive_directory_iterator();

		for (; !ec && it != end; it.increment(ec))
		{
			const std::filesystem::path& path = it->path();

			if (it->is_directory(ec))
			{
				// Skip dotted directories whole: `.assets` (the mesh cache) today, `.compiled`
				// once Phase 4 lands. Derived output is never asset identity, and not walking it
				// is what keeps the scan's cost proportional to authored content.
				std::string name = path.filename().string();
				if (!name.empty() && name.front() == '.')
					it.disable_recursion_pending();
				continue;
			}

			if (AssetMetaSerializer::IsSidecarPath(path))
				continue;

			if (AssetTypeFromExtension(path.extension().string()) == AssetType::None)
				continue;

			assetFiles.push_back(path);
		}

		if (ec)
		{
			GE_CORE_ERROR("Walking '{0}' failed: {1} - {2} assets were indexed before it stopped.",
				root.string(), ec.message(), assetFiles.size());
		}

		std::sort(assetFiles.begin(), assetFiles.end());

		ScanStats stats;
		for (const std::filesystem::path& fullPath : assetFiles)
		{
			std::string pathKey = MakeAssetRelative(fullPath).generic_string();
			AssetType type = AssetTypeFromExtension(fullPath.extension().string());
			EnsureRegistered(pathKey, fullPath, type, &stats);
		}

		// Deliberately one INFO line with every counter on it: "did this boot mint anything?"
		// is the question a scan-derived index has to be able to answer at a glance, and a
		// second run over an unchanged tree must read 0 minted, 0 written.
		GE_CORE_INFO("Asset scan: {0} files, {1} adopted from sidecars, {2} adopted from the legacy "
			"registry, {3} handles minted, {4} sidecars written, {5} quarantined, {6} handle "
			"collisions, {7} types corrected",
			assetFiles.size(), stats.Adopted, stats.AdoptedLegacy, stats.Minted, stats.Written,
			stats.Quarantined, stats.Collisions, stats.TypeCorrected);
	}

	AssetHandle AssetManager::ImportAsset(const std::filesystem::path& relativePath)
	{
		std::string pathKey = relativePath.generic_string();
		auto existing = s_Data.PathToHandle.find(pathKey);
		if (existing != s_Data.PathToHandle.end())
			return existing->second;

		AssetType type = AssetTypeFromExtension(relativePath.extension().string());
		if (type == AssetType::None)
		{
			GE_CORE_WARN("Unsupported asset type for '{0}'", pathKey);
			return InvalidAssetHandle;
		}

		// Reached only for a file the scan did not see - one created since (an extracted `.glb`
		// texture, a generated `.gmat`) or one a scene names that is not on disk.
		AssetHandle handle = EnsureRegistered(pathKey, GetAssetRoot() / relativePath, type, nullptr);
		GE_CORE_INFO("Imported asset '{0}' as {1} (handle {2})",
			pathKey, AssetTypeToString(type), static_cast<uint64_t>(handle));

		return handle;
	}

	AssetHandle AssetManager::GetHandle(const std::filesystem::path& relativePath)
	{
		std::string pathKey = relativePath.generic_string();
		auto it = s_Data.PathToHandle.find(pathKey);
		if (it != s_Data.PathToHandle.end())
			return it->second;
		return InvalidAssetHandle;
	}

	const AssetMetadata* AssetManager::GetMetadata(AssetHandle handle)
	{
		auto it = s_Data.Registry.find(handle);
		if (it == s_Data.Registry.end())
			return nullptr;
		return &it->second;
	}

	AssetType AssetManager::GetAssetType(AssetHandle handle)
	{
		const AssetMetadata* metadata = GetMetadata(handle);
		return metadata ? metadata->Type : AssetType::None;
	}

	namespace {

		// ---- Mesh ---------------------------------------------------------------------
		//
		// No Parse stage, and this one is deferred work rather than a settled answer. Both load
		// paths construct a `Mesh`, whose constructor runs `Build()` and creates bgfx vertex and
		// index buffers, and both build the mesh's materials inline - which pulls textures.
		// Separating them means threading a CPU-side mesh description (vertices, indices,
		// submeshes, material *descriptions* rather than materials) through `MeshImporter.cpp`
		// and `MeshCache.cpp` and deferring `Mesh::Create` to Apply. That is the split Phase 5
		// actually needs - the cgltf parse is the expensive thing that has to leave the main
		// thread - and it is a change the size of a phase, not a step of this one. Named here so
		// Phase 5 starts from a known cost instead of discovering it.
		Ref<Mesh> ApplyMesh(const AssetMetadata& metadata, Scope<AssetParseResult>)
		{
			const std::filesystem::path relativePath = metadata.FilePath;
			const std::filesystem::path fullPath = GetAssetRoot() / relativePath;

			Ref<Mesh> mesh = MeshCache::TryLoad(relativePath, fullPath);
			if (!mesh)
			{
				mesh = MeshImporter::Load(fullPath);
				if (mesh)
					MeshCache::Write(mesh, relativePath, fullPath);
			}

			if (!mesh)
				return nullptr;

			// Here rather than inside MeshImporter, because this is the one point both the cold
			// import and the cache replay pass through - a cached mesh must still get its
			// sidecars, or deleting .meshcache would be the only way to regenerate them.
			//
			// It now runs *before* the manager caches the mesh, where the old code ran after.
			// Safe because GenerateSidecars only ever reaches ImportAsset, never GetAsset<Mesh>:
			// it writes files and registers handles, so nothing in it can re-enter this load.
			MaterialSerializer::GenerateSidecars(mesh, relativePath);
			return mesh;
		}

		// ---- Environment --------------------------------------------------------------
		//
		// No Parse stage either, but unlike Mesh that is the right answer rather than deferred
		// work. The separable CPU part is one `stbi_loadf` of the equirectangular HDR;
		// everything after it is the IBL bake - six cube faces plus prefilter mips rendered
		// through bgfx views - which can never leave the submit thread. Splitting would move a
		// few percent of the cost and take `Environment`'s filepath constructor with it.
		Ref<Environment> ApplyEnvironment(const AssetMetadata& metadata, Scope<AssetParseResult>)
		{
			return Environment::Create((GetAssetRoot() / metadata.FilePath).string());
		}

		// ---- Texture ------------------------------------------------------------------
		//
		// The clean case, and the one that pays: PNG/JPEG decode is the whole CPU cost and it
		// is entirely below the bgfx line.
		struct TextureParse : AssetParseResult
		{
			DecodedImage Image;
		};

		Scope<AssetParseResult> ParseTexture(const AssetMetadata& metadata)
		{
			auto parsed = CreateScope<TextureParse>();
			parsed->Image = TextureImporter::Decode(GetAssetRoot() / metadata.FilePath, false);
			if (!parsed->Image)
				return nullptr;

			return parsed;
		}

		Ref<Texture2D> ApplyTexture(const AssetMetadata&, Scope<AssetParseResult> parsed)
		{
			return TextureImporter::Upload(static_cast<TextureParse&>(*parsed).Image);
		}

		// ---- Material -----------------------------------------------------------------
		//
		// Cached, not path-resolved (the Script/Audio pattern), and the caching is load-bearing
		// rather than a performance choice: instancing merges draws on Ref<Material> *identity*,
		// so two entities sharing one .gmat handle must receive the same Ref or every batch
		// shatters. That is also why Material cannot be given a shared placeholder in Phase 5
		// without thinking about batching first.
		struct MaterialParse : AssetParseResult
		{
			MaterialDesc Desc;
		};

		Scope<AssetParseResult> ParseMaterial(const AssetMetadata& metadata)
		{
			auto parsed = CreateScope<MaterialParse>();
			if (!MaterialSerializer::ReadDesc(GetAssetRoot() / metadata.FilePath, parsed->Desc))
				return nullptr;

			return parsed;
		}

		Ref<Material> ApplyMaterial(const AssetMetadata&, Scope<AssetParseResult> parsed)
		{
			return MaterialSerializer::Build(static_cast<MaterialParse&>(*parsed).Desc);
		}

	}

	void AssetManager::RegisterManagers()
	{
		// The order fixes the dense type ids for this run and has no other meaning; the ids are
		// never persisted, because AssetType - stored by name in a `.meta` - is the durable
		// form. This list has to agree with the GE_ASSET_TYPE declarations in the header, and
		// nothing enforces that beyond the two sitting one file apart.
		AssetManagerRegistry::Register<Mesh>("Mesh", AssetType::StaticMesh,
			nullptr, &ApplyMesh);
		AssetManagerRegistry::Register<Environment>("Environment", AssetType::Environment,
			nullptr, &ApplyEnvironment);
		AssetManagerRegistry::Register<Texture2D>("Texture2D", AssetType::Texture,
			&ParseTexture, &ApplyTexture);
		AssetManagerRegistry::Register<Material>("Material", AssetType::Material,
			&ParseMaterial, &ApplyMaterial);
	}

	void AssetManager::Reload(AssetHandle handle)
	{
		const AssetMetadata* metadata = GetMetadata(handle);
		if (!metadata)
			return;

		// Scene, Script, Audio and Prefab have no manager, so there is nothing to evict - they
		// are path-resolved and their consumers own whatever caching they do.
		IAssetManager* manager = AssetManagerRegistry::Find(metadata->Type);
		if (!manager)
			return;

		// Textures go first, then their owner. Weak caching did not make this ordering
		// unnecessary, which is worth stating because it is tempting to assume it did: the
		// reloaded material or mesh re-resolves its map paths through LoadMaterialMap, which is
		// a GetAsset<Texture2D>, and a texture still cached would be handed straight back. The
		// rule is about the texture cache, not about who owns the material.
		auto evictMaps = [](const Ref<Material>& material)
		{
			if (!material)
				return;

			for (const std::string* mapPath : {
				&material->GetAlbedoMapPath(),
				&material->GetNormalMapPath(),
				&material->GetMetallicRoughnessMapPath() })
			{
				if (mapPath->empty())
					continue;

				AssetHandle textureHandle = GetHandle(*mapPath);
				if (IsAssetHandleValid(textureHandle))
					AssetManagerRegistry::Get<Texture2D>().Evict(textureHandle);
			}
		};

		if (metadata->Type == AssetType::Material)
		{
			evictMaps(AssetManagerRegistry::Get<Material>().Find(handle));
		}
		else if (metadata->Type == AssetType::StaticMesh)
		{
			if (Ref<Mesh> mesh = AssetManagerRegistry::Get<Mesh>().Find(handle))
			{
				for (const Ref<Material>& material : mesh->GetMaterials())
					evictMaps(material);
			}

			// The timestamp check already catches a source edit; this covers "reimport now",
			// where the source is untouched but something it references changed.
			MeshCache::Invalidate(metadata->FilePath);
		}

		manager->Evict(handle);
		GE_CORE_INFO("Reloading asset '{0}'", metadata->FilePath);
	}

	std::vector<AssetCacheStats> AssetManager::GetCacheStats()
	{
		std::vector<AssetCacheStats> stats;
		AssetManagerRegistry::ForEach([&stats](IAssetManager& manager)
		{
			stats.push_back({ manager.TypeName(), manager.ResidentCount(), manager.RetainedCount() });
		});

		return stats;
	}

	void AssetManager::LoadLegacyRegistry()
	{
		std::filesystem::path registryPath = GetAssetRoot() / "AssetRegistry.gr";
		if (!std::filesystem::exists(registryPath))
			return;

		s_Data.LegacyRegistryPresent = true;

		std::stringstream buffer;
		{
			std::ifstream stream(registryPath);
			if (!stream)
				return;

			buffer << stream.rdbuf();
		}

		YAML::Node assets;
		try
		{
			// Same posture as SceneSerializer::Deserialize: malformed content is something to
			// report, not a reason to take the process down. Unhandled, a truncated `.gr`
			// terminated the process out of Init - before a window existed to say why.
			YAML::Node root = YAML::Load(buffer.str());
			assets = root["Assets"];
		}
		catch (const YAML::Exception& e)
		{
			// The file is *not* quarantined, unlike before: nothing overwrites it any more, so
			// leaving it in place is what lets a hand-repair work. What matters instead is that
			// the session must not bake a lossy migration into the tree. An unreadable seed
			// means every asset would mint a fresh handle and write a sidecar claiming it -
			// permanently breaking every scene that referenced the old one. So the session goes
			// read-only: handles still work in memory, nothing is persisted, and fixing the file
			// and restarting recovers completely.
			s_Data.WritableRegistry = false;

			GE_CORE_ERROR("Legacy asset registry '{0}' failed to parse: {1}. assets/ is "
				"read-only for this session so no `.meta` sidecar can be written from a broken "
				"seed - every asset would otherwise adopt a new handle and every existing scene "
				"would stop resolving. Repair or delete the file and restart.",
				registryPath.string(), e.what());
			return;
		}

		if (!assets)
			return;

		for (auto assetNode : assets)
		{
			// `Type` is read past, not read: the extension is what types an asset now, and the
			// by-ordinal enum this file persisted is exactly the trap the sidecar format does
			// not inherit. Only identity is migrated.
			if (!assetNode["Handle"] || !assetNode["FilePath"])
				continue;

			AssetHandle handle = AssetHandle(assetNode["Handle"].as<uint64_t>());
			std::string filePath = assetNode["FilePath"].as<std::string>();

			auto existing = s_Data.LegacyHandles.find(filePath);
			if (existing != s_Data.LegacyHandles.end())
			{
				GE_CORE_WARN("Legacy asset registry has duplicate entries for '{0}' (handles {1} "
					"and {2}); adopting {1}", filePath,
					static_cast<uint64_t>(existing->second), static_cast<uint64_t>(handle));
				continue;
			}

			s_Data.LegacyHandles[filePath] = handle;
		}

		GE_CORE_TRACE("Legacy asset registry read ({0} handles available to adopt)",
			s_Data.LegacyHandles.size());
	}

	bool AssetManager::IsRegistryWritable()
	{
		return s_Data.WritableRegistry;
	}

}
