# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Premake_config = debug
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  yaml_cpp_config = debug
  GanymedEngine_config = debug
  Sandbox_config = debug
  GanymedEditor_config = debug

else ifeq ($(config),release)
  Premake_config = release
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  yaml_cpp_config = release
  GanymedEngine_config = release
  Sandbox_config = release
  GanymedEditor_config = release

else ifeq ($(config),dist)
  Premake_config = dist
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  yaml_cpp_config = dist
  GanymedEngine_config = dist
  Sandbox_config = dist
  GanymedEditor_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Premake GLFW Glad ImGui yaml-cpp GanymedEngine Sandbox GanymedEditor

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad ImGui Premake yaml-cpp

Premake:
ifneq (,$(Premake_config))
	@echo "==== Building Premake ($(Premake_config)) ===="
	@${MAKE} --no-print-directory -C vendor/premake -f Makefile config=$(Premake_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C GanymedEngine/extern/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C GanymedEngine/extern/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C GanymedEngine/extern/imgui -f Makefile config=$(ImGui_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C GanymedEngine/extern/yaml-cpp -f Makefile config=$(yaml_cpp_config)
endif

GanymedEngine: GLFW Glad ImGui yaml-cpp
ifneq (,$(GanymedEngine_config))
	@echo "==== Building GanymedEngine ($(GanymedEngine_config)) ===="
	@${MAKE} --no-print-directory -C GanymedEngine -f Makefile config=$(GanymedEngine_config)
endif

Sandbox: GanymedEngine GLFW Glad ImGui yaml-cpp
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

GanymedEditor: GanymedEngine GLFW Glad ImGui yaml-cpp
ifneq (,$(GanymedEditor_config))
	@echo "==== Building GanymedEditor ($(GanymedEditor_config)) ===="
	@${MAKE} --no-print-directory -C GanymedEditor -f Makefile config=$(GanymedEditor_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/premake -f Makefile clean
	@${MAKE} --no-print-directory -C GanymedEngine/extern/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C GanymedEngine/extern/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C GanymedEngine/extern/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C GanymedEngine/extern/yaml-cpp -f Makefile clean
	@${MAKE} --no-print-directory -C GanymedEngine -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean
	@${MAKE} --no-print-directory -C GanymedEditor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Premake"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   yaml-cpp"
	@echo "   GanymedEngine"
	@echo "   Sandbox"
	@echo "   GanymedEditor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"